import BlogItem from "@/app/components/BlogItem";
import { blogs } from "@/app/data/data";
import Link from "next/link";

const Blogs = () => {
  return (
    <div>
      <ul>
        <li>
          {blogs.map((blog) => (
            <Link
              className="text-white"
              key={blog.id}
              href={`/dashboard/blogs/${blog.id}`}
            >
              <BlogItem blog={blog}/>
            </Link>
          ))}
        </li>
      </ul>
    </div>
  );
};

export default Blogs;

export let metadata = {
    title: "Blogs",
    description: "Generated by create next app",
  };