import { blogs } from "@/app/data/data";
export const generateStaticParams = () => {
  return blogs.map((blog) => {
    id: blog.id;
  });
};
const SingleBlog = ({ params }) => {
  const { id } = params;
  const blogDetail = blogs.find((blog) => blog.id === id);
  metadata.title = "Blog" + "-" + blogDetail.id;

  return (
    <div>
      <h1>{blogDetail.title}</h1>
      <p>{blogDetail.detail}</p>
    </div>
  );
};

export default SingleBlog;

export let metadata = {
  title: "",
  description: "Generated by create next app",
};
