const Analytic = () => {
  return (
    <div>
      <h1 className="mt-5 text-2xl text-orange-600 ">Analytic page</h1>
    </div>
  );
};

export default Analytic;

export const metadata = {
    title: "Analytic",
    description: "Generated by create next app",
  };