import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-4 border-b border-gray-400">
          <ul className="flex gap-5">
            <li>
              <Link href={"/"}>Home</Link>
            </li>

            <li>
              <Link href={"/dashboard/analytics"}>Analytics</Link>
            </li>
            <li>
              <Link href={"/dashboard/contact"}>Contact</Link>
            </li>
          </ul>
        </nav>

        {children}
      </body>
    </html>
  );
}
